import java.io.*;
import java.math.*;
import java.security.*;
import java.text.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.*;



public class Solution {
    public static void main(String[] args) throws IOException {
     
      Scanner sc=new Scanner (System.in);
      int size =sc.nextInt();
      int a[]=new int[size];
      
      for (int i=0;i<size;i++)
      {
          a[i]=sc.nextInt();
      }
      for (int i=size-1;i>=0;i--)
      {
          System.out.print(a[i] + " ");
      }
    }
}
